server:
  port: 8080

zuul:
  routes:
    demo:
      path: /demo/**
      url: http://localhost:9670
    home:
      path: /**
      url: http://localhost:9000

ribbon:
  eureka:
    enabled: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
